apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: corjeftrt-go 
  janus-idp.io/tekton: corjeftrt-go
  backstage.io/kubernetes-id: corjeftrt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: corjeftrt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  